print("Hello Omar")
#print("My name is Omar Essam\n I am 25 years old\n I am embedded engineer \n graduated 2021\n")
#name=input("enter your name:")
#age=int(input("enter your age:"))
##college=input("enter your college:")
#print("name is:",name,"\nage is:",age,"\ncollege is:",college)
#a,b,c=input("enter 3 values").split("x",3)
#print(a)
#x='a'
#print((ord)(x)) #show ascii
x=int(input("enter first no."))
y=int(input("enter second no."))
print(x==y)
print(x<=y)
print (x**2)
print(x+y)
print(x|y)
#print(2.9\\2)
print(2.9//2)